version: 2
updates:
  - package-ecosystem: 'pnpm'
    directory: '/'
    schedule:
      interval: 'weekly'
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-minor"
          - "version-update:semver-patch"

  - package-ecosystem: 'pnpm'
    directory: '/sanity'
    schedule:
      interval: 'weekly'
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-minor"
          - "version-update:semver-patch"
